load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_test(
    name = "controller_test",
    size = "small",
    srcs = ["controller_test.cpp"],
    deps = [
        "//:roo_wifi",
        "@googletest//:gtest_main",
    ],
)
