name=roo_wifi
version=2.0.0
author=Dejwk <dejwk.oss@gmail.com>
maintainer=Dejwk <dejwk.oss@gmail.com>
sentence=Portable Wi-Fi operations and known-key profiles, with an ESP32 ESP-IDF adapter.
paragraph=
category=Communication
url=https://github.com/dejwk/roo_wifi
architectures=esp32
depends=roo_collections,roo_prefs,roo_backport,roo_scheduler
