name=roo_wifi
version=1.1.5
author=Dejwk <dejwk.oss@gmail.com>
maintainer=Dejwk <dejwk.oss@gmail.com>
sentence=WiFi controller library for ESP32, supporting storing persistent configuration in flash, and abstracting away the architecture.
paragraph=
category=Communication
url=https://github.com/dejwk/roo_wifi
architectures=esp32
depends=roo_collections,roo_prefs,roo_backport,roo_scheduler
