package(default_visibility = ["//visibility:public"])

exports_files(["example_build.bzl"])

filegroup(
    name = "all_arduino_example_builds",
    srcs = ["//examples/arduino/scan_networks"],
)

filegroup(
    name = "all_esp_idf_example_builds",
    srcs = ["//examples/esp_idf/scan_networks"],
)
